### ISSUE TITLE
plunkr does not work

### ISSUE THREAD

**Issue by crh225** [Longfld/DynamicalAsyncRouter#1]
Hi, The plunker does not work anymore. Thanks, CH

**Comment by Longfld** [comment]
It works for me. pls try with  your chrome and refresh it

**Comment by crh225** [comment]
You posted two plunker links. This one does not work in chrome: http://plnkr.co/edit/y31K7xbiQSVH59qsAOZF?p=preview

this one does: http://plnkr.co/edit/diZgQ8wttafb4xE6ZUFv?p=preview
